name: App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Setup db
      working-directory: ./server
      run: |
        npm ci
        npm run db:mock-init
    - name: Run tests
      working-directory: ./server
      run: npm run test:e2e
